### ISSUE TITLE
Detect fake lists that use emoji as "list markers"

### ISSUE THREAD

**Issue by mrwweb** [itmaybejj/editoria11y#13]
I came across a fake list made with emojis today and noticed that Editoria11y doesn't catch it. I can see why [in the code since the tests don't include any emoji characters](https://github.com/itmaybejj/editoria11y/blob/main/js/ed11y-test-text.js#L17). Here's what I mean (warning, fake list ahead!):

> Salsa Ingredients:
> 
> 🥑 Avocado
> 🍅 Tomato
> 🌶 Chili pepper
> 🧂 Salt

Fake lists with emoji are definitely "a thing" and I think they're starting to migrate from mostly social sites to websites more generally, and so it would be great to include them in the fake-list tests, if possible. Here's a recent [article noting the issue](https://chriscoyier.net/2023/04/07/emoji-lists-the-good-way/) and evening showing a CSS technique for using real lists!

I admittedly have not given much thought yet to how the test would work, as it would probably need to test for entire unicode ranges and account for complex emoji combinations. If this seems like a potential improvement to Editoria11y, I'd be happy to try to do a bit of research and report back.

**Comment by mrwweb** [comment]
[Matching emoji seems to be quite thorny](https://stackoverflow.com/questions/18862256/how-to-detect-emoji-using-javascript) since it covers a variety of ranges and, importantly, often is more than one character long.

Hearing that this test is already slow and thinking about the potential added complexity, I wonder if we should wait and see if other people are seeing this out in the wild. I did, but maybe it's less common than I fear.

**Comment by itmaybejj** [comment]
Sounds good.

The more I sleep on this -- I could imagine writing a test along the lines of "whether the emoji's name will convey its meaning in context, or whether it is being used for a visual affect that will be confusing to a screen reader user" 

Perhaps if any two paragraphs in a row contain an emoji or any emoji appear several-in-a-row, throw a manual check...

@adamchaboryk -- any thoughts?

**Comment by adamchaboryk** [comment]
I'm pretty sure i've seen an emoji list before! I'll look into it...

**Comment by mrwweb** [comment]
> Perhaps if any two paragraphs in a row contain an emoji or any emoji appear several-in-a-row, throw a manual check...

@itmaybejj You make a very good point that "fake lists" is only one category of emoji accessibility concerns. In general, using too many emoji, especially at the start of sentences/headings/paragraphs is an issue for folks. The [A11y Project brief summary](https://www.a11yproject.com/posts/everyday-accessibility/#limit-your-emojis) is good about this.

> ## Limit your emojis
> Emojis are great for emphasis and playfulness, but adding too many sounds cluttered with text-to-speech software. Also, when placed unconventionally (such as throughout a sentence) this is distracting and hard to read for those with reading difficulties. Keep your emojis to the minimum needed to make your point, group them together, and move them towards the end of any text.
> 
> Key Point:
> 
> Avoid writing: I 👏 know 👏 that’s 👏 right 👏!!!
> 
> Because text-to-speech reads: I [clapping hands] know [clapping hands] that’s [clapping hands] right [clapping hands] !!!

There's a closely related issue around certain unicode symbols like right pointing arrow (→) that get used by some folks. I'll say though that I wonder if it's enough of a problem to be worth flagging. I suspect you try to guard against throwing too many nit-picky issues in order to guard against people writing off _all_ issues the tool flags.

Finally, you also made me think about other issues that are more prevalent on social but increasingly show up on websites which includes the [need to CamelCase hashtags](https://www.a11yproject.com/posts/everyday-accessibility/#use-capital-letters-in-hashtags).

So I wonder if multiple emojis and camel casing are both worth new issues for potential tests.

**Comment by itmaybejj** [comment]
I may circle back for multi-emoji strings.

But in the meantime: got emoji-list detection working!
https://github.com/itmaybejj/editoria11y/blob/main/js/ed11y-test-text.js#L17
