### ISSUE TITLE
Wrong protocol assumed

### ISSUE THREAD

**Issue by HUisHU-Christian** [itmaybejj/editoria11y#14]
In editoria11y-dashboard.js on line 12 the https protocol is assumed. While this might be true for most real websites nowadays, it is not that easy to achieve for localhost development.

This I'd propose to change 

'https://'

with 

window.location.protocol + '://'

**Comment by CWBudde** [comment]
Oh, I noted that it should actually read: window.location.protocol + '//' (as the colon is part of the protocol)

**Comment by itmaybejj** [comment]
[changed in 1.0.12.](https://wordpress.org/plugins/editoria11y-accessibility-checker/#developers)
